# Generated by Django 4.2.7 on 2024-02-16 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="products/images/")),
            ],
            options={
                "verbose_name_plural": "Product Images",
            },
        ),
        migrations.RenameModel(
            old_name="Reviews",
            new_name="ProductReview",
        ),
        migrations.RemoveField(
            model_name="images",
            name="product",
        ),
        migrations.AlterModelOptions(
            name="productreview",
            options={"verbose_name_plural": "Product Reviews"},
        ),
        migrations.RenameIndex(
            model_name="productreview",
            new_name="products_pr_product_eab03a_idx",
            old_name="products_re_product_5d2432_idx",
        ),
        migrations.DeleteModel(
            name="Images",
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="product_images", to="products.product"
            ),
        ),
    ]
