# Generated by Django 4.2.7 on 2024-02-20 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, related_name="orders", to="carts.cart"
            ),
            preserve_default=False,
        ),
    ]
