# Generated by Django 4.2.7 on 2024-02-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("CREATED", "Created"), ("PAID", "Paid"), ("SHIPPED", "Shipped"), ("CANCELED", "Canceled")],
                default="CREATED",
                max_length=10,
            ),
        ),
    ]
