# Generated by Django 4.2.7 on 2024-02-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_stripe_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("CREATED", "Created"), ("PAID", "Paid")], default="CREATED", max_length=10
            ),
        ),
    ]
