version: "3"

volumes:
  ecommerce_local_postgres_data: {}
  ecommerce_local_postgres_data_backups: {}
  ecommerce_django_media: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: ecommerce_local_django
    container_name: ecommerce_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.django
      - ./.envs/.stripe
      - ./.envs/.postgres
    expose:
      - 8000
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: ecommerce_production_postgres
    container_name: ecommerce_local_postgres
    volumes:
      - ecommerce_local_postgres_data:/var/lib/postgresql/data
      - ecommerce_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.postgres

  stripe:
    image: stripe/stripe-cli:v1.19.2
    container_name: ecommerce_local_stripe
    volumes:
      - .:/app:z
    command: listen --forward-to http://django:8000/api/v1/payments/webhooks/
    env_file:
      - ./.envs/.stripe
    depends_on:
      - django
